### PR TITLE
(MAINT) Add dag and workspaces icons

### PR DESCRIPTION
**Pull request by sean-mckenna**
Add 2 new icons. Taken from here - https://www.figma.com/file/9RzmjE0XYWWADWLKOJP5mR/PDS-UI-Components?node-id=17%3A96

dag

Screenshot 2020-10-28 at 18 59 32

workspaces

Screenshot 2020-10-14 at 21 05 09

### CODE REVIEW

**Comment by vine77** [comment]
Thanks @sean-mckenna! I know you didn't design the `dag` logo, but it looks cropped to me and seems like that SVG of a directed acyclic graph is not really a graph if edges don't go anywhere. If it were me, I'd add an extra "parent" square node in there. But if the designer wants it that way, we can always merge and iterate.

**Comment by sean-mckenna** [comment]
@vine77 good point, calling it a dag is maybe a bit misleading here. I believe it’s deliberately designed like that but il CC @jtmuz to confirm before we merge. Thanks.

**Comment by jtmuz** [comment]
I've updated the dag symbol in Figma @sean-mckenna and @vine77. Also attached
[i-16-dag.svg.zip](https://github.com/puppetlabs/design-system/files/5454091/i-16-dag.svg.zip)

**Comment by sean-mckenna** [comment]
@vine77 updated the dag icon with the updated SVG from @jtmuz.

**Review by vine77 — APPROVED** [review]
LGTM!

**Pull request merged**
