### PR TITLE
Adding the Relay logo 

### PR DESCRIPTION
**Pull request by woodburndesigns**
This logo is slightly different in color and style than the others. However, I was still able to use the same API to ensure it renders properly in the correct locations.

### CODE REVIEW

**Comment by nmuldavin** [comment]
We should consider keeping this in the relay repo until we know it's really really final. Has it gone through legal review?

**Comment by woodburndesigns** [comment]
@nmuldavin Going to close this for now.

**Comment by vine77** [comment]
I was going to suggest that we add a copyright notice to Logo.md and/or [to the SVGs](https://stackoverflow.com/questions/38775825/semantically-correct-way-to-add-a-copyright-notice-into-a-svg-file). Otherwise, I'd support adding Relay's current logo.

**Comment by vine77** [comment]
I added a trademark notice to Logo.md (which will render at https://puppet.style/#/React%20Components/Logo) @woodburndesigns:

Screen Shot 2020-05-07 at 4 48 46 PM

I also fixed the centering of the logo in a minimized sidebar (previously it seemed too far to the right):

Screen Shot 2020-05-07 at 4 50 26 PM

**Pull request merged**
