### PR TITLE
Maint add icons

### PR DESCRIPTION
**Pull request by nkanderson**

### CODE REVIEW

**Comment by nkanderson** [comment]
Looking at other examples in this file, it seems like `clip-rule` and `fill` are not necessary or desired. If that's not always the case, let me know and I'll amend these commits (svgo didn't remove those attributes, so I wasn't totally sure...)

**Comment by nkanderson** [comment]
Oh sorry, I wasn't super clear - the resulting svgs after running svgo _did_ contain `clip-rule` and `fill`, but I removed those by hand because it looked like they shouldn't be included (based on the other icons). From what I read, it seemed like `clip-rule` wouldn't be relevant. And I was thinking that the `fill` is maybe applied elsewhere in the component?

**Comment by vine77** [comment]
@nkanderson Gotcha. That's interesting, I guess if there's no `<clipPath>` then `clip-rule` doesn't apply. Yes, `fill` should be removed. I'll add that to the docs "Adding icons to the Design System" section. We do that to allow changing the color via CSS, and default to `$puppet-n600`.

**Comment by nkanderson** [comment]
Perfect, thanks @vine77 !

**Pull request merged**
