### PR TITLE
(LIDAR-555) Add neutral tag

### PR DESCRIPTION
**Pull request by Lukeaber**
The neutral tag component as off designs https://www.figma.com/file/9RzmjE0XYWWADWLKOJP5mR/PDS-UI-Components?node-id=2219%3A3301 .

A few assumptions that have been made:
 - That is was okay to add a iconSize prop to the button component
 - That the tag 'type' prop was the correct prop to use, i know theres talk of changing this prop on the buttons etc. but wasn't sure if that applied here

### CODE REVIEW

**Comment by Lukeaber** [comment]
Screenshot 2020-10-14 at 12 15 29

**Comment by vine77** [comment]
@Sigler What should the props be named here?

**Comment by vine77** [comment]
@Sigler has a matrix for the future of prop naming. It looks like `type` is intended to be reserved for color, so this would be more like `emphasis="subtle"`.

image

**Comment by vine77** [comment]
Let's make this type="neutral" emphasis="subtle" and make the X grey.

**Review by vine77 — CHANGES_REQUESTED** [review]
See comments

**Comment by Lukeaber** [comment]
Screenshot 2020-11-02 at 13 58 10

**Review by vine77 — APPROVED** [review]
LGTM!

**Pull request merged**
