### PR TITLE
Added Wendy's star icons

### PR DESCRIPTION
**Pull request by Sigler**
image

Added new star icons per @wendy-oh and the Estate Reporting team.

* Added star-empty
* Added star-solid

This should fulfill their needs. Note that these icons are different than the `star` icon. That is in use by the forge and has a box around it. We didn't want to overwrite their icon so we've used the new suffixes to indicate the differences. We may want to deprecate `star` in 2.0.

### CODE REVIEW

**Review by caseywilliams — COMMENTED** [review]
Cool, we have some custom star icons on the Forge that we could replace with these - :+1: once the check failures are resolved

**Comment by Sigler** [comment]
i really should remember to test locally first

**Comment by vine77** [comment]
@caseywilliams Are you using the "star" icon in the Forge? Nik added it in https://github.com/puppetlabs/design-system/pull/226 (but it is a star in a box whereas these are just a solid and outlined star).

**Comment by caseywilliams** [comment]
@vine77 yeah, there are multiple star styles in use on the Forge redesigns

**Review by vine77 — APPROVED** [review]
LGTM!

**Pull request merged**
