### PR TITLE
Move react-code-editor into react-components

### PR DESCRIPTION
**Pull request by sprokusk**

### CODE REVIEW

**Comment by nmuldavin** [comment]
We should attempt to fix some of the problems with the code editor, like the fact that you can still edit it in read-only mode, before porting in to the website

**Comment by nmuldavin** [comment]
I also think this is a better candidate for a separate package, or to put in relay-ui before porting here

**Comment by vine77** [comment]
Published as [@puppet/react-code-editor](https://www.npmjs.com/package/@puppet/react-code-editor) 0.1.0.

**Comment by sprokusk** [comment]
@vine77 have you seen that tv show on netflix? the one your gif is from? The Midnight Gospel

**Comment by vine77** [comment]
Haha, yeah I watched the first two episodes. I'm a fan of Pendleton Ward from Adventure Time.

**Pull request merged**
