### PR TITLE
Add Toolbar type variant / update toolbar tabs style

### PR DESCRIPTION
**Pull request by nmuldavin**
* Introduce primary / secondary toolbar. Default is primary which is white. Secondary is what it looked like before, grey
* Fix css bugs with secondary buttons inside toolbar
* Update styling of toolbar tabs to be more consistent with regular tabs (see screenshot)

Screen Shot 2020-06-11 at 10 02 25 AM

### CODE REVIEW

**Comment by nmuldavin** [comment]
Converting to a draft until we can think this through more / reach an agreement. Here's what it looks like https://user-images.githubusercontent.com/6165476/84449813-55a55780-ac03-11ea-9a18-a3b52f03605f.png

**Comment by Sigler** [comment]
Ready to make the call on this one. 

Let's get this one out the door and follow the design as spec'd in https://tickets.puppetlabs.com/browse/PDS-478

**Comment by nmuldavin** [comment]
Which version are you referring to? The one in the screenshot on that ticket with no bottom border?

**Comment by Sigler** [comment]
Yes please :)

**Comment by nmuldavin** [comment]
I don't want to merge it in that state until we've accounted for the downstream effects. It's a change that fundamentally alters the context the toolbar has to be used in, since you can't have stuff directly below the toolbar. The ability to do so was one of the reasons we created the pattern to begin with. 

I'm not saying we're stuck with past decisions forever such that we can't change the intent of the component, but we need to account for the work it creates. We will have to rearrange the content patterns on our main two pages in relay. I think that's your agenda anyways, but we need to account for that work up front rather than creating the problem before a solution.

**Comment by nmuldavin** [comment]
If we're looking to be iterative, I would merge that change but with the bottom border in-tact on the active tab, until we can resolve those layout issues:

Screen Shot 2020-06-12 at 12 30 09 PM

**Comment by Sigler** [comment]
Sounds good to me. I'd rather get a small movement in that direction than nothing at all.
Only thing outstanding would be to address one thing from your screenshot. Tab 1 and 2 being b500 would be even closer to final.

**Pull request merged**
